### ISSUE TITLE
_.any is not a function error

### ISSUE THREAD

**Issue by ikbenivo** [isaacw/framer-animation-collections#3]
Using this animation Set:

```
loadingDots = new AnimationSet
    animations:
        a: loadingDot1Up
        b: loadingDot2Up
        c: loadingDot3Up
    repeat: true

loadingDots.start()
```

http://share.framerjs.com/p6e8mj5tv6ov/

I'm getting this error:
`TypeError: _.any is not a function. (In '_.any(this._animationsArray, "isAnimating", true)', '_.any' is undefined)`
